package se.kth.dd2480;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void appHasAGreeting() {
        Assertions.assertTrue(false);
        // App classUnderTest = new App();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
